language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install . -vv
  - pip install -r test-requirements.txt

script:
  - py.test

after_success:
  - codecov
