language: python
python:
  - "2.7"


addons:
  apt:
    packages:
      - coreutils
      - build-essential
      - gfortran


cache:
  apt: true
  directories:
    - $HOME/.cache/pip

install:
  - pip install . -vv
  - pip install -r test-requirements.txt

script:
  - py.test

after_success:
  - codecov
