language: python
python:
  - "3.7"


addons:
  apt:
    packages:
      - coreutils
      - build-essential
      - gfortran
      - metview


cache:
  apt: true
  directories:
    - $HOME/.cache/pip

install:
  - pipenv install --dev

script:
  - py.test

after_success:
  - codecov
