version: '3.7'

services:
  core:
    build:
      context: .
      dockerfile: Dockerfile.core

    image: onyb/ecpoint-calibrate-core

    volumes:
      # Forward UNIX domain sockets
      - /tmp/.X11-unix:/tmp/.X11-unix

      # Mount externally plugged devices
      - /media:/media

      # Mount home directory of host as /root
      - $HOME:/root

    environment:
      - DISPLAY=$DISPLAY

    devices:
      - /dev/dri:/dev/dri

    command: wait-for-it logger:9001 --timeout=5 -- python -m core.api

    ports:
      - 8888:8888
  electron:
    build:
      context: .
      dockerfile: Dockerfile.electron

    image: onyb/ecpoint-calibrate-electron

    volumes:
      # Forward UNIX domain sockets
      - /tmp/.X11-unix:/tmp/.X11-unix

      # Mount externally plugged devices
      - /media:/media

      # Mount home directory of host as /root
      - $HOME:/root

    environment:
      - DISPLAY=$DISPLAY
      - DOCKER=1

    devices:
      - /dev/dri:/dev/dri

    command: wait-for-it core:8888/healthcheck --timeout=5 -- npm start

  logger:
    build:
      context: .
      dockerfile: Dockerfile.logger

    image: onyb/ecpoint-calibrate-logger

    volumes:
      # Mount externally plugged devices
      - /media:/media

      # Mount home directory of host as /root
      - $HOME:/root

    ports:
      - 9001:9001
