version: '3.7'

services:
  core:
    image: onyb/ecpoint-calibrate-core:legacy

    volumes:
      # Mount externally plugged devices
      - /media:/media

      # Mount home directory of host as /root
      - $HOME:/root

      # Mount host tmp directory of host as /tmp
      - /tmp:/tmp

    command: wait-for-it logger:9001 --timeout=5 -- pipenv run server

    ports:
      - 8888:8888


  electron:
    shm_size: "2gb"

    image: onyb/ecpoint-calibrate-electron:legacy

    volumes:
      # Forward UNIX domain sockets
      - /tmp/.X11-unix:/tmp/.X11-unix

      # Mount externally plugged devices
      - /media:/media

      # Mount home directory of host as /root
      - $HOME:/root

      # Mount host tmp directory of host as /tmp
      - /tmp:/tmp

      # Workaround for Electron's "Out of memory" issues
      - /dev/shm:/dev/shm

    environment:
      - DISPLAY=$DISPLAY
      - DOCKER=1
      - NODE_OPTIONS="--max-old-space-size=8192"
      - ENV=production

    devices:
      - /dev/dri:/dev/dri

    command: wait-for-it core:8888/healthcheck --timeout=5 -- npm start -- --no-sandbox

  logger:
    shm_size: "2gb"

    image: onyb/ecpoint-calibrate-logger:legacy

    volumes:
      # Mount externally plugged devices
      - /media:/media

      # Mount home directory of host as /root
      - $HOME:/root

      # Workaround for Electron's "Out of memory" issues
      - /dev/shm:/dev/shm

    ports:
      - 9001:9001
