version: 2
jobs:
  build:
    machine:
        docker_layer_caching: true
    docker:
      - image: circleci/buildpack-deps:disco

    steps:
      - checkout

      - run:
          command: sudo apt-get update && apt-get install -y metview libmetview-dev python3 python3-pip

      - run:
          command: pip3 install -U pip pipenv

      - run:
          command: pipenv install --dev --system --three
      - run:
          command: pipenv run "py.test && codecov"
