version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:disco

    steps:
      - restore_cache:
          keys:
            - source-v2-{{ .Branch }}-{{ .Revision }}
            - source-v2-{{ .Branch }}-
            - source-v2-
      - checkout
      - save_cache:
          key: source-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - run:
          command: |
            sudo apt-get update
            sudo apt-get install -y metview libmetview-dev python3 python3-pip
            sudo ln -s /usr/lib/x86_64-linux-gnu/libMv* /usr/lib/
            sudo ln -s /usr/lib/x86_64-linux-gnu/libMetview* /usr/lib/

      - run:
          command: sudo pip3 install -U pip pipenv

      - restore_cache:
          key: pipenvdeps-{{ checksum "Pipfile.lock" }}
      - run:
          command: pipenv install --dev
      - save_cache:
          key: pipenvdeps-{{ checksum "Pipfile.lock" }}
          paths:
            - pipenv --venv

      - run:
          command: pipenv run test

      - run:
          command:
            pipenv run codecov
