name: ecpoint-pycal
version: '0.1.0'
summary: Calibration Software in Python developed at ECMWF
description: |
  [TODO] - This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # [TODO] - must be 'stable' to release into candidate/stable channels
confinement: devmode # [TODO] - use 'strict' once the right plugs and slots have been defined

parts:
  electron:
    plugin: nodejs
    node-engine: 8.11.2
    npm-run: [ build ]
    source: .

    build-packages:
      - libgdk-pixbuf2.0-dev

    stage-packages:
      - libpng-dev
      - zlib1g-dev
      - libx11-6
      - libxau6
      - libxdmcp6
      - libxext6
      - libxcb1
      - libxtst6
      - libgtk-3-0
      - libxss1
      - libgconf-2-4
      - libnss3
      - libasound2

    override-build: |
      snapcraftctl build
      touch $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
      chmod +w $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
      gdk-pixbuf-query-loaders > $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache


    organize:
      usr/bin: bin
      lib/node_modules/ecPoint-PyCal: app

    filesets:
      binaries:
        - bin/*
        - app/node_modules/.bin/electron

      so:
        - lib

      runtime_node_modules:
        - lib/node_modules/npm
        - app/node_modules/electron

    after: [ core ]

  core:
    plugin: python
    python-version: python2

    build-packages:
      - gfortran
      - cmake
      - gsettings-desktop-schemas

    source: .

    override-build: |
      snapcraftctl build
      bash install_eccodes.sh

    stage-packages:
      - python-tk

apps:
  my-snap-name:
    command: npm start --prefix $SNAP/app
    plugs:
      - browser-support
      - desktop
      - home
      - wayland
      - x11
